server:
  port: 8080
  

spring:
  application:
    name: lms-backend
    mongodb:
      uri: mongodb://localhost:27017/lms_db # We will use Docker later, localhost for now
      auto-index-creation: true # Helps creates indexes automatically